# Python Doesn't Have Good Numeric Support
* Python integers are actually an object with header and typing information
* access to Python integers requires a level of indirection
* In C, integers are directly accessible in memory without indirection
<img src="https://github.com/osipov/edu/raw/master/pyt0/images/python-01.png" width=700 height=400>

## The Problem is Even Worse for Python Lists 
* Python lists are immensely flexible
  * no fixed size
  * OK to have heterogeneous data
* ...but as a result they are not likely to be contiguous in memory
* and even if they are, there is still a lot of indirection required
* so they aren't good for fast number crunching
<img src="https://github.com/osipov/edu/raw/master/pyt0/images/python-02.png" width=700 height=700>

In [1]:
pylist = list(range(1_000_000))
%timeit [i + 1 for i in pylist]

10 loops, best of 5: 98.8 ms per loop


## One solution is to use PyTorch tensors
* written in C++
* allows for vectorized operations

In [2]:
import torch as pt
pt.__version__

'1.10.0+cu111'

## PyTorch Scalars

In [3]:
pt.tensor(42)

tensor(42)

In [4]:
pt.tensor(42).dtype

torch.int64

In [5]:
pt.tensor(42).shape

torch.Size([])

In [6]:
len(pt.tensor(42).shape) == 0

True

In [7]:
pt.tensor(3.14).dtype

torch.float32

In [8]:
pt.tensor(3.14).item()

3.140000104904175

In [9]:
pt.tensor(3.14).item() == 3.14

False

## IEEE Standard for Floating-Point Arithmetic (IEEE 754) 
* a refresher on floating point precision issues

In [10]:
x = 0.3
x

0.3

In [11]:
3 * 0.1 == x

False

In [12]:
3 * 0.1

0.30000000000000004

In [13]:
x = pt.tensor(3.14)

In [14]:
x.to(pt.uint8).item()

3

In [15]:
pt.tensor(x.to(pt.uint8))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor(3, dtype=torch.uint8)

In [16]:
pt.tensor(x.to(pt.uint8).item(), dtype = pt.float32)

tensor(3.)

## __pt.trunc()__

* nearest integer __`i`__ which is closer to zero than __`x`__ is

In [17]:
pt.trunc(x)

tensor(3.)

In [18]:
pt.trunc(pt.tensor(2.01)).dtype

torch.float32

## __pt.floor()__

* the largest integer __`i`__, such that __`i <= x`__

In [19]:
pt.floor(x)

tensor(3.)

In [20]:
pt.floor(pt.tensor(2.01))

tensor(2.)

In [21]:
pt.floor(pt.tensor(2.))

tensor(2.)

In [22]:
pt.floor(pt.tensor(-3.14))

tensor(-4.)

## __pt.ceil()__

* the smallest integer __`i`__, such that __`i >= x`__

In [23]:
pt.ceil(x)

tensor(4.)

In [24]:
pt.ceil(pt.tensor(2.01))

tensor(3.)

In [25]:
pt.ceil(pt.tensor(2.))

tensor(2.)

* can __pt.ceil()__ be used in place of __pt.floor()__ ?

In [26]:
pt.ceil(x) - 1

tensor(3.)

In [27]:
pt.ceil(pt.tensor(2.01)) - 1

tensor(2.)

In [28]:
pt.ceil(pt.tensor(2.)) - 1

tensor(1.)

## PyTorch arrays
* data is stored contiguously in memory

In [29]:
# pytorch will infer the data type
a = pt.tensor([1, 4, 2, 5, 3])
a, a.dtype

(tensor([1, 4, 2, 5, 3]), torch.int64)

In [30]:
a = pt.tensor([3.14, 4, 2, 3])
a, a.dtype

(tensor([3.1400, 4.0000, 2.0000, 3.0000]), torch.float32)

In [31]:
# ...or you can be explicit
a = pt.tensor([1, 2, 3, 4], dtype=pt.float32)
a

tensor([1., 2., 3., 4.])

In [32]:
pt.tensor([range(i, i + 3) for i in [2, 4, 6]])

tensor([[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]])

In [33]:
pt.zeros(10, dtype=int)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
pt.ones((3, 5), dtype=float)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [35]:
pt.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [36]:
pt.full((3, 5), 42, dtype=int)

tensor([[42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42]])

In [37]:
pt.arange(0, 20, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
pt.linspace(0, 1, 5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

## Pseudo-Random Numbers

In [39]:
pt.manual_seed(0);

In [40]:
pt.randn(3, 3)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])

In [41]:
pt.normal(0, 1, size = (3, 3))


tensor([[-0.4033, -0.5966,  0.1820],
        [-0.8567,  1.1006, -1.0712],
        [ 0.1227, -0.5663,  0.3731]])

In [42]:
pt.randint(0, 10, (3, 3))

tensor([[2, 9, 1],
        [8, 8, 3],
        [6, 9, 1]])

## Converting array types

In [ ]:
x = pt.linspace(0, 10, 50)
x

In [ ]:
x.to(int)

## Multi-dimensional Arrays

In [ ]:
x2 = pt.randint(10, size=[3, 4])
x2

## True "matrix-style" indexing

In [ ]:
x2[0, 0]

In [ ]:
x2[2, 0]

In [ ]:
x2[2, -1]

In [ ]:
x2[0, 0] = 12
x2

In [43]:
pt.arange(0, 9).reshape(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Array Slicing

In [44]:
x = pt.arange(10)
x[:5]

tensor([0, 1, 2, 3, 4])

In [45]:
x[5:]

tensor([5, 6, 7, 8, 9])

In [46]:
x[4:7]

tensor([4, 5, 6])

In [47]:
x[::2]

tensor([0, 2, 4, 6, 8])

In [48]:
x[1::2]

tensor([1, 3, 5, 7, 9])

In [ ]:
x[::-1] # :)

In [ ]:
reversed(x)

In [ ]:
reversed(x)[5::2]

## Filtering 1-dimensional data

In [ ]:
x = pt.tensor([ 1, 0, 5, 2, 1, 0, 8, 0, 0 ])

In [ ]:
x.nonzero()

In [ ]:
x[x.nonzero()]

In [49]:
x[x < 3]

tensor([0, 1, 2])

## Filtering 2-dimensional data

In [51]:
x = pt.tensor([[1, 0, 0], [0, 5, 0], [7, 8, 0]])
x

tensor([[1, 0, 0],
        [0, 5, 0],
        [7, 8, 0]])

In [52]:
# produces two arrays, one with x coords, one with y coords
x.nonzero()

tensor([[0, 0],
        [1, 1],
        [2, 0],
        [2, 1]])

In [53]:
x.nonzero(as_tuple = True)

(tensor([0, 1, 2, 2]), tensor([0, 1, 0, 1]))

In [54]:
x[x.nonzero(as_tuple = True)]

tensor([1, 5, 7, 8])

In [55]:
y = pt.arange(1, 10).reshape(3, 3)
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
y.index_select(dim = 0, index = pt.tensor([0, 2]))

tensor([[1, 2, 3],
        [7, 8, 9]])

In [57]:
y.index_select(dim = 1, index = pt.tensor([0, 2]))

tensor([[1, 3],
        [4, 6],
        [7, 9]])

In [58]:
y.triu()

tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])

In [59]:
y.tril()

tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])

In [60]:
y.tril().T #transpose

tensor([[1, 4, 7],
        [0, 5, 8],
        [0, 0, 9]])

## Multi-dimensional subarrays

In [61]:
x2

NameError: ignored

In [ ]:
x2[:2, :3]

In [ ]:
x2[:3, ::2]

In [ ]:
x2[::-1, ::-1]

In [ ]:
reversed(x2)

In [ ]:
indices = pt.arange(x2.numel() - 1, -1, -1)
indices

In [ ]:
pt.take(x2, indices).reshape(x2.shape) #x2[::-1, ::-1]

## Subarray Views

In [ ]:
x2, id(x2)

In [ ]:
x2_sub = x2[:2, :2]
x2_sub, id(x2_sub)

In [ ]:
x2_sub[0, 0] = 99
x2_sub

In [ ]:
x2 # changes x2 as well, since the subarray has references to the original

## PyTorch ATen Functions
* operate on tensors as on contiguous blobs of data in memory
* _vectorized_ wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs

| Operator | ATen            | Description                         |
|----------|-----------------|-------------------------------------|
|   +      | pt.add          | Addition (e.g., 1 + 1 = 2)          |
|   -      | pt.subtract     | Subtraction (e.g., 3 - 2 = 1)       |
|   -      | pt.negative     | Unary negation (e.g., -2)           |
|   *      | pt.multiply     | Multiplication (e.g., 2 * 3 = 6)    |
|   /      | pt.divide       | Division (e.g., 3 / 2 = 1.5)        |
|   //     | pt.floor_divide | Floor division (e.g., 3 // 2 = 1)   |
|   **     | pt.power        | Exponentiation (e.g., 2 ** 3 = 8)   |
|   %      | pt.mod          | Modulus/remainder (e.g., 9 % 4 = 1) |

## Vectorized Operations

In [62]:
pytorch = pt.arange(1_000_000)
%timeit pytorch + 1

The slowest run took 8.19 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 5: 2.2 ms per loop


In [ ]:
x = pt.arange(9).reshape((3, 3))
2 ** x

In [ ]:
x = pt.arange(4)
-(0.5 * x + 1) ** 2

## Exponents and Logarithms 

In [ ]:
x = pt.tensor([1., 2., 3.])
pt.exp(x)

In [ ]:
pt.pow(3, x)

In [ ]:
pt.log(pt.tensor([1., 2., 3.]))

In [ ]:
pt.log2(pt.tensor([1., 256., 65536.]))

In [ ]:
pt.log10(pt.tensor([1_000., 1_000_000., 10. ** 10]))

## Aggregations

In [ ]:
x = pt.arange(15).reshape(3, 5)
x

In [ ]:
x.sum()

In [ ]:
x.sum(dim = 0)

In [ ]:
x.sum(dim = 1, keepdims = True)

In [ ]:
x.sum(dim = 1)

In [ ]:
x.to(float).mean(), x.to(float).std()

Copyright 2021 CounterFactual.AI LLC. Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.